name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true 
          fetch-depth: 0

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: public